- name: Check if Docker is installed
  command: docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'
  register: docker_ver
  ignore_errors: true
  changed_when: false

- name: Display Docker version
  debug:
    msg: "Docker version: {{ docker_ver.stdout | default('not installed') }}"

- name: Install Docker if necessary
  shell: curl -fsSL https://raw.githubusercontent.com/Stensel8/basic-scripts/refs/heads/main/docker_installer.sh | sudo bash
  when: docker_ver.rc != 0 or (docker_ver.stdout is version(required_docker, '<'))
  notify: Restart Docker

- name: Wait until Docker is available
  command: docker info
  register: docker_info
  retries: 5
  delay: 3
  until: docker_info.rc == 0
  changed_when: false

- name: Ensure Docker is running and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
