- name: Start MySQL container
  docker_container:
    name: mysql
    image: mysql:8.0.13
    env:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomlapassword
    ports:
      - '3306:3306'
    state: started
    restart_policy: always

- name: Start Joomla container
  docker_container:
    name: joomla
    image: joomla:latest
    env:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomlapassword
      JOOMLA_DB_NAME: joomla
    links:
      - mysql:mysql
    ports:
      - '80:80'
    state: started
    restart_policy: always