# This playbook enables user accounts and restricts their ability to change passwords.
# It targets Windows servers specified in the inventory under the 'windows_servers' group.
# User details are retrieved from an external variables file named 'users.yml'.
# The 'win_domain_user' module is used to configure each user account in the loop.
---
- name: Enable users and restrict password change
  hosts: windows_servers
  gather_facts: no
  vars_files:
    - users.yml

  tasks:
    - name: Enable user accounts and restrict password change
      microsoft.ad.user:
        name: "{{ item.firstname }}.{{ item.lastname }}"
        enabled: yes
        user_cannot_change_password: yes
      loop: "{{ users }}"
