---
- name: Deploy Joomla and its Database using Docker
  hosts: klantA_joomla
  become: true

  vars:
    docker_db_container: "joomla_db"
    docker_joomla_container: "joomla_app"
    mariadb_image: "mariadb:11.7.2"
    joomla_image: "joomla:php8.1-apache"
    db_root_password: "joomla_root_pw"
    db_user: "joomla"
    db_password: "joomla_pw"
    db_name: "joomla"
    mariadb_port: "3306"
    joomla_http_port: "80" 
    # Define the minimum required Docker version (adjust as needed)
    required_docker_version: "27.3.1"

  tasks:
    - name: Install pip if not already installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install Python package 'requests' for Docker interactions
      ansible.builtin.pip:
        name: requests
        state: present

    - name: Check if Docker is installed and get its server version
      command: "docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'"
      register: docker_version
      ignore_errors: yes
      changed_when: false

    - name: Show installed Docker version
      debug:
        msg: "Installed Docker version: {{ docker_version.stdout | default('not installed') }}"

    - name: Install Docker if not installed or version is older than required
      shell: curl -fsSL https://raw.githubusercontent.com/Stensel8/basic-scripts/refs/heads/main/docker_installer.sh | sudo bash
      when: docker_version.rc != 0 or (docker_version.stdout is version(required_docker_version, '<'))
      notify: Restart Docker

    - name: Wait for Docker to be available after installation
      command: docker info
      register: docker_info
      retries: 5
      delay: 3
      until: docker_info.rc == 0
      changed_when: false

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Deploy MariaDB container for Joomla
      community.docker.docker_container:
        name: "{{ docker_db_container }}"
        image: "{{ mariadb_image }}"
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
        published_ports:
          - "{{ mariadb_port }}:3306"
        volumes:
          - "/var/lib/{{ docker_db_container }}:/var/lib/mysql"

    - name: Deploy Joomla container
      community.docker.docker_container:
        name: "{{ docker_joomla_container }}"
        image: "{{ joomla_image }}"
        state: started
        restart_policy: always
        links:
          - "{{ docker_db_container }}:db"
        env:
          JOOMLA_DB_HOST: "db:3306"
          JOOMLA_DB_USER: "{{ db_user }}"
          JOOMLA_DB_PASSWORD: "{{ db_password }}"
          JOOMLA_DB_NAME: "{{ db_name }}"
        published_ports:
          - "{{ joomla_http_port }}:80"
        volumes:
          - "/var/www/joomla:/var/www/html"

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
