---
- name: Allow ICMP Traffic from LAN
  hosts: pfsense
  gather_facts: no
  collections:
    - pfsensible.core

  vars:
    pfsensible_url: "https://192.168.1.1/"
    pfsensible_verify_ssl: false
    pfsensible_username: "admin"
    pfsensible_password: "pfsense"

  tasks:
    - name: Allow ICMP (ping) traffic from LAN
      pfsense_rule:
        name: "Allow LAN ICMP Traffic"
        state: present
        interface: lan
        action: pass
        source: "192.168.1.0/24"
        destination: any
        protocol: icmp
        icmptype: echo-request
